### ISSUE TITLE
move to meson build system

### ISSUE THREAD

**Issue by trichter** [paudetseis/Telewavesim#49]
Occasionally we should move from `numpy.distutils` to meson. I think telewavesim cannot be installed alongside python3.12 due to setuptools/numpy.distutils conflicts. numpy.distutils is also removed from numpy.

**Comment by khannema** [comment]
Hi there,
I have troubles installing telewavesim as I run in the following error, while trying to install it via pip:

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "~/src/Telewavesim/setup.py", line 3, in <module>
          from numpy.distutils.core import setup, Extension
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

As I think this is related to the issue trichter pointed out above I hope someone knows a way to fix this.

**Comment by trichter** [comment]
As a work-around you can try to install in a conda environment with an old numpy and python version.

The following is working for me:
```
conda create -n telews "python=3.10" "numpy<1.22" obspy pytest fortran-compiler
conda activate telews
pip install telewavesim
pytest -v --pyargs telewavesim  # run tests
```

**Comment by khannema** [comment]
Thank you for your quick reply, we did the same here as a workaround and setup an environment with python 3.10.

**Comment by paudetseis** [comment]
On MacOS (x64), the above work-around installation still fails. I have found that the following works, using much earlier versions:

```
conda create -n telews -c conda-forge "python=3.7" "numpy<1.21" obspy pytest fortran-compiler
conda activate telews
pip install telewavesim
```

I started a branch `scikit` that repackages Telewavesim to build using the `sciki-build-core` back-end, but I am struggling with how to link the LAPACK libraries. Any hint is appreciated!

**Comment by paudetseis** [comment]
I created a PR in a branch `v030` with a working meson build, which works with `python=3.12`. You can install it using: 

`pip install git+https://github.com/paudetseis/telewavesim.git@v030`

The CI fails with `pytest` as the tests are not yet incorporated in the build. I will merge the PR once the tests are working.

**Comment by paudetseis** [comment]
@trichter I added the tests to the package build, but they fail in the deployment because the symbol `dgeev_` (from the LAPACK library) cannot be found. It seems this is a linking problem, but it doesn't happen when I install and run the tests locally. 

Can you try installing the code from `v030` and run the tests? I wonder if this is a problem with the GH actions that require more details to link the LAPACK library, or with Ubuntu. 

The GH build log says "Run-time dependency lapack found: NO (tried pkgconfig, framework and cmake)", but I also get this message when I build locally, and it still installs properly and successfully runs the tests. 

Thanks for your help!

**Comment by paudetseis** [comment]
I just tested the branch on Ubuntu 20.04.6 LTS, and the installation and tests work fine. There is something funny going on in the GH actions that makes the tests fail, so I'll just comment out those lines for now in `test.yml` and merge `v030` to `master`. We can figure out later what causes the failed tests in the GH actions.

**Comment by trichter** [comment]
The old v0.2.2 version is working for me, Debian 6.12.

Unfortunately, v0.3.0 does not work yet. I created the environment following the readme.

```
$ pip install git+https://github.com/paudetseis/telewavesim
Collecting git+https://github.com/paudetseis/telewavesim
  Cloning https://github.com/paudetseis/telewavesim to /tmp/pip-req-build-38ciivrh
  Running command git clone --filter=blob:none --quiet https://github.com/paudetseis/telewavesim /tmp/pip-req-build-38ciivrh
  Resolved https://github.com/paudetseis/telewavesim to commit e0702bbefedd4476da428192f295881af77b9494
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20895 lines of output]
      + meson setup /tmp/pip-req-build-38ciivrh /tmp/pip-req-build-38ciivrh/.mesonpy-tjr_2g1r -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-req-build-38ciivrh/.mesonpy-tjr_2g1r/meson-python-native-file.ini
      The Meson build system
      Version: 1.8.0
      Source dir: /tmp/pip-req-build-38ciivrh
      Build dir: /tmp/pip-req-build-38ciivrh/.mesonpy-tjr_2g1r
      Build type: native build
      Project name: telewavesim
      Project version: 0.3.0
      C compiler for the host machine: cc (gcc 15.1.0 "cc (conda-forge gcc 15.1.0-2) 15.1.0")
      C linker for the host machine: cc ld.bfd 2.43
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Fortran compiler for the host machine: gfortran (gcc 15.1.0 "GNU Fortran (conda-forge gcc 15.1.0-2) 15.1.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.43
      Program python found: YES (/data/fass5/eule/.anaconda/envs/test_telewavesim2/bin/python3.12)
      Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
      Run-time dependency python found: YES 3.12
      Run-time dependency lapack found: YES 0.3.21+ds
      Build targets in project: 3
      
      telewavesim 0.3.0
      
        User defined options
          Native files: /tmp/pip-req-build-38ciivrh/.mesonpy-tjr_2g1r/meson-python-native-file.ini
          b_ndebug    : if-release
          b_vscrt     : md
          buildtype   : release
      
      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-62l5ph44/normal/bin/ninja
      + /tmp/pip-build-env-62l5ph44/normal/bin/ninja
      [1/10] Generating rmat_fmodule.c with a custom command
      Reading fortran codes...
          Reading file '../src/rmat_sub.f90' (format:free)
          Reading file '../src/rmat.f90' (format:free)
      Post-processing...
          Block: rmat_f
                          Block: layer
                          Block: addit
                          Block: xeveci
                          Block: isotroc
                          Block: anisotroc
                          Block: xinv3
                          Block: rxinv3
                          Block: xmult3
                          Block: sort_evec
                          Block: reorder_evec
                          Block: sort_r
                          Block: cnorm
                          Block: conf
      In: :rmat_f:../src/rmat.f90:conf
      param_eval: got "eval() arg 1 must be a string, bytes or code object" on 8
                          Block: rmat
                                  Block: rmatrix
      In: :rmat_f:../src/rmat.f90:rmat:rmatrix
      param_eval: got "eval() arg 1 must be a string, bytes or code object" on 8
                                  Block: rtfluid
      In: :rmat_f:../src/rmat.f90:rmat:rtfluid
      param_eval: got "eval() arg 1 must be a string, bytes or code object" on 8
                          Block: plane
                                  Block: plane_land
      In: :rmat_f:../src/rmat.f90:plane:plane_land
      param_eval: got "eval() arg 1 must be a string, bytes or code object" on 8
      In: :rmat_f:../src/rmat.f90:plane:plane_land
      analyzevars: could not parse dimension for variable 'int(nt/2)+1'
      In: :rmat_f:../src/rmat.f90:plane:plane_land
      analyzevars: could not parse dimension for variable 'int(nt/2)+1'
      In: :rmat_f:../src/rmat.f90:plane:plane_land
      analyzevars: could not parse dimension for variable 'int(nt/2)+1'
      In: :rmat_f:../src/rmat.f90:plane:plane_land
      analyzevars: could not parse dimension for variable 'int(nt/2)+1'
                                  Block: plane_obs
      In: :rmat_f:../src/rmat.f90:plane:plane_obs
      param_eval: got "eval() arg 1 must be a string, bytes or code object" on 8
      In: :rmat_f:../src/rmat.f90:plane:plane_obs
      analyzevars: could not parse dimension for variable 'int(nt/2)+1'
      Applying post-processing hooks...
        character_backward_compatibility_hook
      Post-processing (stage 2)...
          Block: rmat_f
                  Block: unknown_interface
                          Block: layer
                          Block: addit
                          Block: xeveci
                          Block: isotroc
                          Block: anisotroc
                          Block: xinv3
                          Block: rxinv3
                          Block: xmult3
                          Block: sort_evec
                          Block: reorder_evec
                          Block: sort_r
                          Block: cnorm
                          Block: conf
                          Block: rmat
                                  Block: rmatrix
                                  Block: rtfluid
                          Block: plane
                                  Block: plane_land
                                  Block: plane_obs
      Building modules...
          Building module "rmat_f"...
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "layer"...
                layer(omega,xh,eval,tu,td,rd)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "addit"...
                addit(nlay,ilay,tus,rus,tds,rds,tu,ru,td,rd)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "xeveci"...
                xeveci(evec,eveci)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "isotroc"...
                isotroc(vp,vs,dens,p11,p22,q,n)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "anisotroc"...
                anisotroc(c,dens,p11,p22,q,n)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "xinv3"...
                xinv3(a,ainv)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "rxinv3"...
                rxinv3(a,ainv)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "xmult3"...
                xmult3(a,b,c)
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "sort_evec"...
                sort_evec(q,evec,[n])
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "reorder_evec"...
                reorder_evec(evalr,evali,evecr,eveci,indx,eval,evec,[n])
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "sort_r"...
                sort_r(a,indx,[m,n])
          Generating possibly empty wrappers"
          Maybe empty "rmat_f-f2pywrappers.f"
              Constructing wrapper function "cnorm"...
                cnorm(n,[nm])
                  Constructing F90 module support for "conf"...
                    Variables: pi nlaymx a thickn rho dp c rhof isoflg dt slow baz evals evecs tui rui tdi rdi
                  Constructing F90 module support for "rmat"...
                  Constructing wrapper function "rmat.rmatrix"...
                    tus,rus,tds,rds = rmatrix(px,py,omega,nlay,iter)
                  Constructing wrapper function "rmat.rtfluid"...
                    rtmat = rtfluid(p1,p2,a0,b0,rhos)
                  Constructing F90 module support for "plane"...
                  Constructing wrapper function "plane.plane_land"...
                    yx,yy,yz = plane_land(nt,nlay,wvtype)
                  Constructing wrapper function "plane.plane_obs"...
                    yx,yy,yz = plane_obs(nt,nlay,wvtype)
          Wrote C/API module "rmat_f" to file "./rmat_fmodule.c"
          Fortran 90 wrappers are saved to "./rmat_f-f2pywrappers2.f90"
      [2/10] Scanning target rmat_f.cpython-312-x86_64-linux-gnu for modules
      [3/10] Compiling C object lib_fortranobject.a.p/9886d29a060ed24e1bbc7d87bfe1655bf1aa4d33_site-packages_numpy_f2py_src_fortranobject.c.o
      [4/10] Linking static target lib_fortranobject.a
      [5/10] Generating dynamic dependency information for target rmat_f.cpython-312-x86_64-linux-gnu
      [6/10] Compiling C object rmat_f.cpython-312-x86_64-linux-gnu.so.p/meson-generated_.._rmat_fmodule.c.o
      FAILED: rmat_f.cpython-312-x86_64-linux-gnu.so.p/meson-generated_.._rmat_fmodule.c.o
      cc -Irmat_f.cpython-312-x86_64-linux-gnu.so.p -I. -I.. -I/tmp/pip-build-env-62l5ph44/overlay/lib/python3.12/site-packages/numpy/_core/include -I/tmp/pip-build-env-62l5ph44/overlay/lib/python3.12/site-packages/numpy/f2py/src -I/data/fass5/eule/.anaconda/envs/test_telewavesim2/include/python3.12 -I/usr/include/x86_64-linux-gnu -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -Wno-incompatible-pointer-types -fPIC -MD -MQ rmat_f.cpython-312-x86_64-linux-gnu.so.p/meson-generated_.._rmat_fmodule.c.o -MF rmat_f.cpython-312-x86_64-linux-gnu.so.p/meson-generated_.._rmat_fmodule.c.o.d -o rmat_f.cpython-312-x86_64-linux-gnu.so.p/meson-generated_.._rmat_fmodule.c.o -c rmat_fmodule.c
      In file included from /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/features.h:375,
                       from /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:24,
                       from /data/fass5/eule/.anaconda/envs/test_telewavesim2/include/python3.12/Python.h:23,
                       from rmat_fmodule.c:18:
      /usr/include/x86_64-linux-gnu/sys/cdefs.h:146:55: error: missing binary operator before token '('
        146 | #if __USE_FORTIFY_LEVEL == 3 && (__glibc_clang_prereq (9, 0)                  \
            |                                                       ^
      /usr/include/x86_64-linux-gnu/sys/cdefs.h:636:49: error: missing binary operator before token '('
        636 | #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
            |                                                 ^
      /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:95:22: error: expected ';' before 'typedef'
         95 | __BEGIN_NAMESPACE_STD
            |                      ^
            |                      ;
         96 | /* Returned by `div'.  */
         97 | typedef struct
            | ~~~~~~~
      /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:112:1: error: unknown type name '__END_NAMESPACE_STD'
        112 | __END_NAMESPACE_STD
            | ^~~~~~~~~~~~~~~~~~~
      /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:117:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__extension__'
        117 | __extension__ typedef struct
            | ^~~~~~~~~~~~~
      /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:123:20: error: expected ';' before 'extern'
        123 | __END_NAMESPACE_C99
            |                    ^
            |                    ;
      ......

... a lot of more lines ...

      /data/fass5/eule/.anaconda/envs/test_telewavesim2/x86_64-conda-linux-gnu/sysroot/usr/include/stdio.h:53:1: error: old-style parameter declarations in prototyped function definition
         53 | __USING_NAMESPACE_STD(FILE)
            | ^~~~~~~~~~~~~~~~~~~~~
      rmat_fmodule.c:3132: error: expected '{' at end of input
      rmat_fmodule.c:3132: warning: control reaches end of non-void function [-Wreturn-type]
      [7/10] Compiling Fortran object rmat_f.cpython-312-x86_64-linux-gnu.so.p/src_rmat_sub.f90.o
      [8/10] Compiling Fortran object rmat_f.cpython-312-x86_64-linux-gnu.so.p/src_rmat.f90.o
      ninja: build stopped: subcommand failed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
